enableColors: true

nmHoistingLimits: workspaces

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.2.3.cjs

npmScopes:
  "0xlighthouse":
    # npmAlwaysAuth: true
    # npmAuthToken:
    npmRegistryServer: "https://npm.pkg.github.com"
