enableColors: true

nmHoistingLimits: workspaces

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.2.3.cjs

# https://github.com/yarnpkg/berry/issues/1641#issuecomment-1014510372
npmScopes:
  "0xlighthouse":
    npmAlwaysAuth: true
    npmAuthToken: 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
    npmRegistryServer: "https://npm.pkg.github.com"
